### ISSUE TITLE
Add common Jenkinsfile

### ISSUE THREAD

**Issue by yrodiere** [hibernate/hibernate-search-performance#2]
Just to run the build and tests.

Maybe also add an integration test that runs the banchmark for a single, very fast iteration, similar to https://github.com/hibernate/hibernate-search/blob/3de5a26fc6fd9cd10f94aa6ea20fc48e3a187a2b/integrationtest/performance/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/performance/backend/elasticsearch/SmokeIT.java#L32

Useful for pull requests and such.

**Comment by fax4ever** [comment]
Here is a build: https://ci.hibernate.org/job/hibernate-search-performance/job/common-integration-test/
